apiVersion: apps/v1
kind: Deployment
metadata:
  name: carpe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carpe
  template:
    metadata:
      labels:
        app: carpe
    spec:
      containers:
        - name: carpe
          image: gcr.io/carpe-355217/carpe:v1
          ports:
            - containerPort: 8080