name: Carpe GKE CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
      # env vars
      - name: Set up environment variables
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
          echo "MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" >> $GITHUB_ENV
          echo "OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}" >> $GITHUB_ENV
          echo "OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "JWT_EXPIRY=${{ secrets.JWT_EXPIRY }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # Build with Maven
      - name: Build with Maven
        run: mvn -f carpe-be/carpe/pom.xml clean package -DskipTests

      # Set up Google Cloud authentication
      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Docker to use Google Cloud Registry
      - name: Configure Docker to use Google Container Registry
        run: |
          echo "Login to gcr.io"
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/carpe:latest -f carpe-be/carpe/Dockerfile .

      # Push the Docker image to Google Container Registry
      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/carpe:latest

      # Set up Google Kubernetes Engine (GKE)
      - name: Set up GKE
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_ZONE }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Update the image in the Kubernetes deployment
      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/carpe-be carpe-be=gcr.io/${{ secrets.GCP_PROJECT_ID }}/carpe:latest --record
          kubectl set env deployment/carpe-be MONGODB_URI=${{ secrets.MONGODB_URI }}
          kubectl set env deployment/carpe-be MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}
          kubectl set env deployment/carpe-be OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}
          kubectl set env deployment/carpe-be OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}
          kubectl set env deployment/carpe-be JWT_SECRET=${{ secrets.JWT_SECRET }}
          kubectl set env deployment/carpe-be JWT_EXPIRY=${{ secrets.JWT_EXPIRY }}
      

      # Rollout restart to ensure pods use the latest image
      - name: Rollout restart deployment
        run: |
          kubectl rollout restart deployment/carpe-be

      # Optional: Verify that the deployment was successful
      - name: Check rollout status
        run: |
          kubectl rollout status deployment/carpe-be
